--- #YAML:1.0
name:               Deep-Encode
version:            0.06
abstract:           Perl extension for  coding and decoding strings in arrays and hashes ( recursive )
author:
    - A. G. Grishaev <grian@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
